### ISSUE TITLE
Owncloud sync connection failed

### ISSUE THREAD

**Issue by cgrima** [cgrima/arche-server#10]
Exception: {"Message":"HTTP\/1.1 400 expected filesize 5242880 got 311296","Exception":"Sabre\DAV\Exception\BadRequest","Code":0,"Trace":"#0 \/var\/www\/html\/lib\/private\/connector\/sabre\/file.php(101): OC\Connector\Sabre\File->createFileChunked(Resource id #33)\n#1 \/var\/www\/html\/lib\/private\/connector\/sabre\/directory.php(115): OC\Connector\Sabre\File->put(Resource id #33)\n#2 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\Connector\Sabre\Directory->createFile('paper.zip-chunk...', Resource id #33)\n#3 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\DAV\Server->createFile('Perso\/Documents...', Resource id #33, NULL)\n#4 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#5 \/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\Event\EventEmitter->emit('method:PUT', Array)\n#7 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#8 \/var\/www\/html\/apps\/files\/appinfo\/remote.php(56): Sabre\DAV\Server->exec()\n#9 \/var\/www\/html\/remote.php(137): require_once('\/var\/www\/html\/a...')\n#10 {main}","File":"\/var\/www\/html\/lib\/private\/connector\/sabre\/file.php","Line":361}

**Comment by cgrima** [comment]
Try the "Upload limit" workaround (Settings > Network > Upload Bandwidth > Limit automatically) in the sync client's settings

from https://github.com/owncloud/core/issues/9832#issuecomment-68443113
